import React from "react";
import jsPDF from "jspdf";
import * as XLSX from "xlsx";
import "../styles/Gamification.css";

function ExportReport() {

  const reportData = [
    {
      Category: "Overall ESG Score",
      Value: "85%"
    },
    {
      Category: "Environmental Score",
      Value: "90%"
    },
    {
      Category: "Social Score",
      Value: "82%"
    },
    {
      Category: "Governance Score",
      Value: "84%"
    },
    {
      Category: "Employee XP",
      Value: "850"
    },
    {
      Category: "Badge Earned",
      Value: "ESG Champion"
    },
    {
      Category: "Top Department",
      Value: "IT Department"
    },
    {
      Category: "AI Recommendation",
      Value: "Reduce travel emissions and improve sustainability activities"
    }
  ];


  // PDF Export
  const downloadPDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("EcoSphere AI", 20, 25);

    doc.setFontSize(16);
    doc.text("ESG Sustainability Report", 20, 35);

    doc.line(20, 40, 190, 40);


    doc.setFontSize(12);

    let y = 55;

    reportData.forEach((item) => {

      doc.text(
        `${item.Category}:`,
        20,
        y
      );

      doc.text(
        item.Value,
        80,
        y
      );

      y += 12;

    });


    doc.setFontSize(10);
    doc.text(
      "Generated by EcoSphere AI Copilot",
      20,
      280
    );


    doc.save("EcoSphere_ESG_Report.pdf");
  };



  // Excel Export
  const downloadExcel = () => {

    const worksheet =
      XLSX.utils.json_to_sheet(reportData);


    const workbook =
      XLSX.utils.book_new();


    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      "ESG Report"
    );


    XLSX.writeFile(
      workbook,
      "EcoSphere_ESG_Report.xlsx"
    );
  };



  return (
    <div className="card">

      <h2>📄 ESG Report Export</h2>

      <button onClick={downloadPDF}>
        Download PDF Report
      </button>

      <button onClick={downloadExcel}>
        Download Excel Report
      </button>

    </div>
  );
}

export default ExportReport;